import { Page, Text, View, Document, StyleSheet, pdf } from '@react-pdf/renderer'
import { saveAs } from './saveAs'

const styles = StyleSheet.create({
  page: { padding: 40, backgroundColor: '#FFFFFF', fontSize: 10, fontFamily: 'Helvetica' },
  brand: { fontSize: 22, color: '#1A1410', marginBottom: 4, fontWeight: 'bold' },
  tagline: { fontSize: 10, color: '#8E4A2F', marginBottom: 24, letterSpacing: 2 },
  h: { fontSize: 14, marginTop: 16, marginBottom: 8, color: '#1A1410' },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  bold: { fontWeight: 'bold' },
  hr: { borderBottomWidth: 1, borderBottomColor: '#E8C68F', marginVertical: 12 },
  total: { fontSize: 16, color: '#1A1410', marginTop: 16 },
  small: { fontSize: 9, color: '#666' },
})

export function InvoiceDoc({ invoice }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>CREATINK</Text>
        <Text style={styles.tagline}>CREATOR LINK</Text>

        <Text style={styles.h}>Tax Invoice</Text>
        <View style={styles.row}><Text style={styles.bold}>Invoice #</Text><Text>{invoice.invoice_no}</Text></View>
        <View style={styles.row}><Text style={styles.bold}>Date</Text><Text>{invoice.date}</Text></View>
        <View style={styles.row}><Text style={styles.bold}>Deal Reference</Text><Text>{invoice.deal_ref}</Text></View>

        <View style={styles.hr} />

        <Text style={styles.h}>From (Creator)</Text>
        <Text>{invoice.creator_legal_name}</Text>
        <Text style={styles.small}>PAN: {invoice.creator_pan}</Text>
        {invoice.creator_gst && <Text style={styles.small}>GST: {invoice.creator_gst}</Text>}

        <Text style={styles.h}>Bill To (Brand)</Text>
        <Text>{invoice.brand_name}</Text>
        <Text style={styles.small}>GST/PAN: {invoice.brand_gst_pan}</Text>

        <View style={styles.hr} />

        <Text style={styles.h}>Line item</Text>
        <View style={styles.row}><Text>{invoice.description}</Text><Text>₹ {invoice.subtotal.toLocaleString('en-IN')}</Text></View>
        {invoice.gst_pct > 0 && (
          <View style={styles.row}><Text>GST @ {invoice.gst_pct}%</Text><Text>₹ {invoice.gst_amount.toLocaleString('en-IN')}</Text></View>
        )}
        <View style={styles.hr} />
        <View style={styles.row}><Text style={styles.total}>Total</Text><Text style={styles.total}>₹ {invoice.total.toLocaleString('en-IN')}</Text></View>

        <Text style={[styles.small, { marginTop: 28 }]}>
          Generated by Creatink. This invoice is generated on behalf of the creator. Creatink is a discovery and
          communication platform; tax compliance is the parties' own responsibility.
        </Text>
      </Page>
    </Document>
  )
}

export async function downloadInvoice(invoice) {
  const blob = await pdf(<InvoiceDoc invoice={invoice} />).toBlob()
  saveAs(blob, `creatink-invoice-${invoice.invoice_no}.pdf`)
}
